export const cartConstants = {
  ADD_PRODUCT_TO_CART_PENDING: 'ADD_PRODUCT_TO_CART_PENDING',
  ADD_PRODUCT_TO_CART_RESOLVED: 'ADD_PRODUCT_TO_CART_RESOLVED',
  ADD_PRODUCT_TO_CART_REJECTED: 'ADD_PRODUCT_TO_CART_REJECTED'
}